config/routes.rb
Railsgirls::Application.routes.draw do
  devise_for :users
  resources :comments

  get "pages/info"
  root :to => redirect('/ideas')
  resources :fruits

  resources :ideas

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :idea
end

app/models/fruit.rb
class Fruit < ActiveRecord::Base
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all
    render 'index'
  end

  def show
    @comment = Comment.find(params[:id])
    render 'show'
  end

  def new
    @comment = Comment.new
    render 'new'
  end

  def edit
    @comment = Comment.find(params[:id])
    render 'edit'
  end

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to :back, notice: 'Comment was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to @comment, notice: 'Comment was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to comments_url, notice: 'Comment was successfully destroyed.'
  end

  private
  # Only allow a trusted parameter "white list" through.
  def comment_params
    params.require(:comment).permit(:user_name, :body, :idea_id)
  end

end

app/controllers/fruits_controller.rb
class FruitsController < ApplicationController

  def index
    @fruits = Fruit.all
    render 'index'
  end

  def show
    @fruit = Fruit.find(params[:id])
    render 'show'
  end

  def new
    @fruit = Fruit.new
    render 'new'
  end

  def edit
    @fruit = Fruit.find(params[:id])
    render 'edit'
  end

  def create
    @fruit = Fruit.new(fruit_params)

    if @fruit.save
      redirect_to @fruit, notice: 'Fruit was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    @fruit = Fruit.find(params[:id])
    if @fruit.update(fruit_params)
      redirect_to @fruit, notice: 'Fruit was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @fruit = Fruit.find(params[:id])
    @fruit.destroy
    redirect_to fruits_url, notice: 'Fruit was successfully destroyed.'
  end

  private
  # Only allow a trusted parameter "white list" through.
  def fruit_params
    params.require(:fruit).permit(:shape, :description, :season, :rank)
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  def index
    @ideas = Idea.all
    render 'index'
  end

  def show
    @idea = Idea.find(params[:id])
    @comment = @idea.comments.build
    render 'show'
  end

  def new
    @idea = Idea.new
    render 'new'
  end

  def edit
    @idea = Idea.find(params[:id])
    render 'edit'
  end

  def create
    @idea = Idea.new(idea_params)

    if @idea.save
      redirect_to @idea, notice: 'Idea was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    @idea = Idea.find(params[:id])
    if @idea.update(idea_params)
      redirect_to @idea, notice: 'Idea was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    redirect_to ideas_url, notice: 'Idea was successfully destroyed.'
  end

  private
  # Only allow a trusted parameter "white list" through.
  def idea_params
    params.require(:idea).permit(:name, :description, :picture)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <%= f.hidden_field :idea_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Body</th>
      <th>Idea</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.idea_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Idea:</strong>
  <%= @comment.idea_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/fruits/_form.html.erb
<%= form_for(@fruit) do |f| %>
  <% if @fruit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fruit.errors.count, "error") %> prohibited this fruit from being saved:</h2>

      <ul>
      <% @fruit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shape %><br>
    <%= f.text_field :shape %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :season %><br>
    <%= f.text_field :season %>
  </div>
  <div class="field">
    <%= f.label :rank %><br>
    <%= f.number_field :rank %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fruits/edit.html.erb
<h1>Editing fruit</h1>

<%= render 'form' %>

<%= link_to 'Show', @fruit %> |
<%= link_to 'Back', fruits_path %>

app/views/fruits/index.html.erb
<h1>Listing fruits</h1>

<table>
  <thead>
    <tr>
      <th>Shape</th>
      <th>Description</th>
      <th>Season</th>
      <th>Rank</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @fruits.each do |fruit| %>
      <tr>
        <td><%= fruit.shape %></td>
        <td><%= fruit.description %></td>
        <td><%= fruit.season %></td>
        <td><%= fruit.rank %></td>
        <td><%= link_to 'Show', fruit %></td>
        <td><%= link_to 'Edit', edit_fruit_path(fruit) %></td>
        <td><%= link_to 'Destroy', fruit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fruit', new_fruit_path %>

app/views/fruits/new.html.erb
<h1>New fruit</h1>

<%= render 'form' %>

<%= link_to 'Back', fruits_path %>

app/views/fruits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shape:</strong>
  <%= @fruit.shape %>
</p>

<p>
  <strong>Description:</strong>
  <%= @fruit.description %>
</p>

<p>
  <strong>Season:</strong>
  <%= @fruit.season %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @fruit.rank %>
</p>

<%= link_to 'Edit', edit_fruit_path(@fruit) %> |
<%= link_to 'Back', fruits_path %>

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-width" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-width" %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-success form-top-margin" %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1>Listing ideas</h1>

<% @ideas.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |idea| %>
      <div class="span4">
        <td><%= image_tag idea.picture_url(:thumb) if idea.picture? %></td>
        <h4><%= link_to idea.name, idea %></h4>
        <%= idea.description %>
      </div>
    <% end %>
  </div>
<% end %>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="span6">
    <%= image_tag(@idea.picture_url, :width => "100%") if @idea.picture.present? %>
  </div>

  <div class="span6">
    <p><b>Name: </b><%= @idea.name %></p>
    <p><b>Description: </b><%= @idea.description %></p>
    <p>
      <%= link_to 'Edit', edit_idea_path(@idea) %> |
      <%= link_to 'Destroy', @idea, confirm: 'Are you sure?', method: :delete %> |
      <%= link_to 'Back', ideas_path %>
    </p>
  </div>
</div>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsgirls</title>
  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css" />
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <ul class="nav navbar-nav">
        <li <% if controller.action_name == "index" %>class="active"<% end %>><a href="/ideas">Ideas</a></li>
        <li <% if controller.action_name == "new" %>class="active"<% end %>><%= link_to 'New Idea', new_idea_path %></li>
        <li <% if controller.action_name == "info" %>class="active"<% end %>><%= link_to 'About', pages_info_path %></li>
      </ul>
      <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as 
        <%= image_tag current_user.gravatar_url, class: "gravatar" %>
          <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>     
      </p>  
  </div>
</nav>
<div class="container">
<% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>
  <%= yield %>
</div>
<footer>
  <div class="container">
    Rails Girls 2014
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>
</body>
</html>

app/views/pages/info.html.erb
<h1>Info about me</h1>
<p>Bacon ipsum dolor sit amet aliqua strip steak voluptate fatback ex, anim exercitation drumstick cillum t-bone. Velit ball tip in jerky leberkas ut frankfurter hamburger aliqua. Aliquip officia kevin tenderloin, drumstick sed pastrami leberkas esse filet mignon. Occaecat elit qui in meatloaf shoulder frankfurter ball tip exercitation. Doner dolore aute, t-bone voluptate ham salami kielbasa. Spare ribs short loin bacon, brisket ball tip kielbasa meatloaf turducken pariatur reprehenderit ea. Ut consequat nisi magna prosciutto venison labore turducken aliqua.

Brisket in andouille, bacon porchetta do consectetur ham hock. Voluptate eiusmod in, cow pork chop sunt jowl eu salami venison pork loin. Porchetta reprehenderit bacon occaecat, in shankle minim commodo esse laboris ham hock. Andouille ea aute deserunt shoulder spare ribs capicola venison minim pork loin occaecat kielbasa flank anim in. Shank do id pork pancetta, veniam cow ham hock nostrud culpa strip steak tongue.

Sirloin tail venison sed sunt pig porchetta incididunt do irure. Excepteur rump pig, meatball proident in laboris. Ut t-bone nostrud leberkas tri-tip veniam dolore kevin ball tip excepteur sunt sirloin in adipisicing aliqua. Chuck est nulla, deserunt exercitation laboris pancetta non drumstick ut tail shank reprehenderit. Eiusmod tempor labore, excepteur anim porchetta corned beef.

Bresaola ut sunt consequat. Cupidatat tongue bresaola, nisi reprehenderit aute quis est duis kevin eiusmod corned beef salami dolore. Ham velit adipisicing pork belly jowl short loin pork loin. Pork belly jerky pancetta, ea nulla adipisicing jowl tri-tip ullamco exercitation boudin elit.

Shank velit beef ribs, bresaola hamburger et corned beef ad pork loin exercitation eiusmod. Ground round pork loin filet mignon, pork ut boudin ham. Cillum jerky esse shankle meatloaf occaecat, pork loin in ribeye andouille landjaeger meatball magna quis. Tempor id rump ut pig. Nisi pork belly corned beef in chuck do in ribeye, duis exercitation anim pancetta dolore bacon. Sunt id ham hock porchetta swine aute pastrami tenderloin spare ribs turducken venison nostrud nulla. Cillum tail esse ex pork, meatball filet mignon ball tip salami corned beef nisi laborum sed shoulder.b</p>